### ISSUE TITLE
CRITICAL: Det går att bryta mot en sanity check

### ISSUE THREAD

**Issue by WilliamFrisk** [Lee4-M/TDA553-lab-grupp36#4]
Eftersom metoden nedan är public går det att sätta currentSpeed till vilket värde som helst.

https://github.com/Lee4-M/TDA553-lab1-grupp36/blob/8c00e8956743e6539c032eb14190cdcc94c3f663/src/car/Car.java#L41-L43

**Comment by Lee4-M** [comment]
Tog bort setCurrentSpeed, använde den för våra tester. Vi använder oss av gas och brake istället nu.

**Comment by WilliamFrisk** [comment]
Inte riktigt löst eftersom increment och decrementSpeed fortfarande är public. Jag skulle t.ex. kunna stoppa in ett värde på -100 i incrementSpeed() och få en negativ hastighet...

**Comment by WilliamFrisk** [comment]
Snyggt!
